language: python
sudo: false
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - git clone https://github.com/didadadida93/primordial.git
  - cd primordial
  - python setup.py sdist --format=zip
  - cd dist
  - pip install primordial-1.0.0.zip
  - cd ../..
  - coverage run -m unittest discover
after_success:
  - codecov
